### ISSUE TITLE
Finding out the gender

### ISSUE THREAD

**Issue by Rahul-Sindhu** [resemble-ai/Resemblyzer#17]
Hey Corentin, It is mentioned that we can use component analysis for gender indentification, could you please guide me on what needs to be done.
Also, I'm getting mixed results for the clustering demo, could you guess what could be wrong here and how to go about fixing it.
![Figure_1](https://user-images.githubusercontent.com/17232527/70615489-81368d80-1c32-11ea-8849-e9b7e90c356a.png)

Thanks!

**Comment by CorentinJ** [comment]
The clustering is entirely done by umap, so it's umap itself that determines the clusters. Since it is non deterministic you will get different outcomes and you cannot trust to always get a male-female separation in general. The point of that demo is to show that it's possible, but I've not implemented the additional steps that would make it possible in general.

Here is what I had in mind:
- Among the speaker embeddings, label a few of each gender (e.g. 3 males, 3 females).
- Use UMAP to reduce the dimensionality, but reduce it to 10 components instead of 2, so as to preserve more structure.
- Then use a clustering algorithm that can leverage the existing labels to form the right clusters

**Comment by Honghe** [comment]
Meet the same problem, with default running of this repo.
![image](https://user-images.githubusercontent.com/1092722/71390458-73720680-263b-11ea-81fd-a5d97ccd1967.png)
