### ISSUE TITLE
Getting different clusters for the same speaker

### ISSUE THREAD

**Issue by Rahul-Sindhu** [resemble-ai/Resemblyzer#19]
Hey,

I tried the projection demo with my own voice recorded files (SpeakerA), and it seems I'm getting overlapping and the clusters are spread far apart, what do you think could be the issue, and how can I go about fixing it?

![Screenshot_20191231_130521](https://user-images.githubusercontent.com/17232527/71613889-c06f5300-2bce-11ea-9dde-0aec48edb08e.png)

![Screenshot_20191231_131010](https://user-images.githubusercontent.com/17232527/71613934-edbc0100-2bce-11ea-8ed4-7186ba087590.png)

Thanks

**Comment by CorentinJ** [comment]
Pass `min_dist=1` [here](https://github.com/resemble-ai/Resemblyzer/blob/master/demo03_projection.py#L30), it will disable the automatic clustering of UMAP so that you can better visualize how spread your data really is.

Ensure you have at least 4-5 samples so that your embeddings are not regarded as outliers by UMAP.
