### ISSUE TITLE
EER of pre-trained model?

### ISSUE THREAD

**Issue by felixkreuk** [resemble-ai/Resemblyzer#48]
Hi, thanks for this repository.
I understand that the speaker embedding model is based on "Generalized End-To-End Loss for Speaker Verification" and was trained on VoxCeleb2.
Could you please mention what is the EER of your pre-trained model?

Thank you

**Comment by CorentinJ** [comment]
Refer to the end of page 19 in [my thesis](https://matheo.uliege.be/handle/2268.2/6801).

EER evaluation was probably the shakiest part of my work, mainly because I couldn't find details of the procedure in the literature. If you're looking to have a metric to report in an academic context, I'd highly recommend you reproduce it on your own. And if you do, I'm interested in the results.

**Comment by felixkreuk** [comment]
I was actually interested in using your speaker encoder for generation purposes. Your demo sounds quite good, but having an objective metric is always nice :)
